/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.bloomu.codeglosser.View;

import java.io.File;
import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.function.Consumer;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.openide.util.Exceptions;

/**
 *
 * @author Louis
 */
public class ProjectFileViewer extends javax.swing.JPanel {

    private static final Logger LOG = Logger.getLogger(ProjectFileViewer.class.getName());
    
    /**
     * Creates new form ProjectFileViewer
     */
    public ProjectFileViewer() {
        initComponents();
    }
    
    public void setDirectory(File dir) {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(dir.getPath());
        try {
            forEachFile(dir, root);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        DefaultTreeModel model = (DefaultTreeModel) projectTree.getModel();
        model.setRoot(root);
    }
    
    private void forEachFile(File dir, DefaultMutableTreeNode root) throws IOException {
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir.toPath())) {
            LOG.info("Successfully opened File Stream for " + dir.toString());
            for (Path p : stream) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(p.toString());
                root.add(n);
                
                File f = p.toFile();
                if (f.isDirectory()) {
                    forEachFile(f, n);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        projectTree = new javax.swing.JTree();

        jScrollPane1.setViewportView(projectTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree projectTree;
    // End of variables declaration//GEN-END:variables
}
