/* BSD 3-Clause License
 *
 * Copyright (c) 2017, Louis Jenkins <LouisJenkinsCS@hotmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     - Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     - Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *     - Neither the name of Louis Jenkins, Bloomsburg University nor the names of its 
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.bloomu.codeglosser.View;

import edu.bloomu.codeglosser.Events.Event;
import io.reactivex.Observable;
import io.reactivex.subjects.PublishSubject;

/**
 *
 * @author Louis Jenkins
 * 
 * The parent of all properties, which manages PropertiesFile, PropertiesTemplate,
 * PropertiesAttributes, and PropertiesSelector. Due to technical difficulties
 * with NetBeans, we reserve space for all attributes and add them manually. 
 */
public class MarkupProperties extends javax.swing.JPanel {
    
    // Event Multiplexer
    private final PublishSubject<Event> event = PublishSubject.create();

    public MarkupProperties() {
        initComponents();
        
        // Handle receiving events
        
        
    }
    
    /**
     * Registers the following observable as an event source. This must be called
     * to receive events from other components.
     * @param source 
     */
    public void addEventSource(Observable<Event> source) {
        source.subscribe(event::onNext);
    }
    
    private void sendEventToFiles(int eventTag, Object data) {
        event.onNext(Event.of(Event.MARKUP_PROPERTIES, Event.PROPERTIES_FILES, eventTag, data));
    }
    
    private void sendEventToTemplates(int eventTag, Object data) {
        event.onNext(Event.of(Event.MARKUP_PROPERTIES, Event.PROPERTIES_TEMPLATES, eventTag, data));
    }
    
    private void sendEventToAttributes(int eventTag, Object data) {
        event.onNext(Event.of(Event.MARKUP_PROPERTIES, Event.PROPERTIES_ATTRIBUTES, eventTag, data));
    }
    
    private void sendEventToSelector(int eventTag, Object data) {
        event.onNext(Event.of(Event.MARKUP_PROPERTIES, Event.PROPERTIES_SELECTOR, eventTag, data));
    }
    
    private void sendEventToController(int eventTag, Object data) {
        event.onNext(Event.of(Event.MARKUP_PROPERTIES, Event.MARKUP_CONTROLLER, eventTag, data));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        propertySelector = new edu.bloomu.codeglosser.View.propertyNoteName();
        propertyAttributes = new edu.bloomu.codeglosser.View.PropertyAttributes();
        tabbedTreeView = new javax.swing.JTabbedPane();
        propertyFiles = new edu.bloomu.codeglosser.View.PropertyTreeView();
        propertyTemplates = new edu.bloomu.codeglosser.View.PropertyTreeView();

        jInternalFrame1.setVisible(true);

        tabbedTreeView.addTab(org.openide.util.NbBundle.getMessage(MarkupProperties.class, "MarkupProperties.propertyFiles.TabConstraints.tabTitle"), propertyFiles); // NOI18N
        tabbedTreeView.addTab(org.openide.util.NbBundle.getMessage(MarkupProperties.class, "MarkupProperties.propertyTemplates.TabConstraints.tabTitle"), propertyTemplates); // NOI18N

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(propertySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(propertyAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedTreeView)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabbedTreeView, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private edu.bloomu.codeglosser.View.PropertyAttributes propertyAttributes;
    private edu.bloomu.codeglosser.View.PropertyTreeView propertyFiles;
    private edu.bloomu.codeglosser.View.propertyNoteName propertySelector;
    private edu.bloomu.codeglosser.View.PropertyTreeView propertyTemplates;
    private javax.swing.JTabbedPane tabbedTreeView;
    // End of variables declaration//GEN-END:variables
}
